"""add_volume_bonus_payments

Revision ID: 4328cb5647d0
Revises: a055c0880c5c
Create Date: 2026-03-17 23:11:19.586901
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4328cb5647d0'
down_revision: Union[str, None] = 'a055c0880c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volume_bonus_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volume_bonus_payments')
    # ### end Alembic commands ###
