"""initial schema

Revision ID: 49ac8090cf6a
Revises: 
Create Date: 2026-02-09 19:55:49.496683
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '49ac8090cf6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('commission_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('payment_frequency', sa.String(length=20), nullable=True),
    sa.Column('paid_to', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('company_source', sa.String(length=100), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('id_number', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('sign_date', sa.Date(), nullable=True),
    sa.Column('recruitment_type', sa.String(length=50), nullable=True),
    sa.Column('product', sa.String(length=100), nullable=True),
    sa.Column('fund_policy_number', sa.String(length=50), nullable=True),
    sa.Column('employment_status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.String(length=20), nullable=True),
    sa.Column('receiving_company', sa.String(length=100), nullable=True),
    sa.Column('track', sa.String(length=100), nullable=True),
    sa.Column('transferring_fund', sa.String(length=100), nullable=True),
    sa.Column('transferring_body', sa.String(length=100), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('expected_raw', sa.Text(), nullable=True),
    sa.Column('actual_raw', sa.Text(), nullable=True),
    sa.Column('amount_difference', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('transfer_date', sa.Date(), nullable=True),
    sa.Column('management_fee', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('lead_source', sa.String(length=100), nullable=True),
    sa.Column('agent_number', sa.String(length=20), nullable=True),
    sa.Column('rights_assignment_date', sa.Date(), nullable=True),
    sa.Column('general_notes', sa.Text(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('commission_paid', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('commission_expected', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('reconciliation_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['file_uploads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_client_records_id_number', 'client_records', ['id_number'], unique=False)
    op.create_index('ix_client_records_receiving_company', 'client_records', ['receiving_company'], unique=False)
    op.create_index('ix_client_records_reconciliation_status', 'client_records', ['reconciliation_status'], unique=False)
    op.create_index('ix_client_records_upload_id', 'client_records', ['upload_id'], unique=False)
    op.create_index('ix_client_records_user_id', 'client_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_client_records_user_id', table_name='client_records')
    op.drop_index('ix_client_records_upload_id', table_name='client_records')
    op.drop_index('ix_client_records_reconciliation_status', table_name='client_records')
    op.drop_index('ix_client_records_receiving_company', table_name='client_records')
    op.drop_index('ix_client_records_id_number', table_name='client_records')
    op.drop_table('client_records')
    op.drop_table('file_uploads')
    op.drop_table('commission_rates')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
