"""add_production_nifraim_columns

Revision ID: 4e172183f374
Revises: 49ac8090cf6a
Create Date: 2026-02-11 22:15:55.550077
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4e172183f374'
down_revision: Union[str, None] = '49ac8090cf6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_records', sa.Column('product_type', sa.String(length=100), nullable=True))
    op.add_column('client_records', sa.Column('total_premium', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('client_records', sa.Column('product_status', sa.String(length=20), nullable=True))
    op.add_column('client_records', sa.Column('fund_type', sa.String(length=100), nullable=True))
    op.add_column('client_records', sa.Column('fund_number', sa.String(length=50), nullable=True))
    op.add_column('client_records', sa.Column('month_end_balance', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('client_records', sa.Column('annual_commission_pct', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('client_records', sa.Column('monthly_commission_pct', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('client_records', sa.Column('commission_before_fee', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('file_uploads', sa.Column('format_type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_uploads', 'format_type')
    op.drop_column('client_records', 'commission_before_fee')
    op.drop_column('client_records', 'monthly_commission_pct')
    op.drop_column('client_records', 'annual_commission_pct')
    op.drop_column('client_records', 'month_end_balance')
    op.drop_column('client_records', 'fund_number')
    op.drop_column('client_records', 'fund_type')
    op.drop_column('client_records', 'product_status')
    op.drop_column('client_records', 'total_premium')
    op.drop_column('client_records', 'product_type')
    # ### end Alembic commands ###
