"""add production summaries

Revision ID: 8d8f02d23630
Revises: b4cefe3b81b5
Create Date: 2026-04-18 23:05:22.944680
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8d8f02d23630'
down_revision: Union[str, None] = 'b4cefe3b81b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('period_label', sa.String(length=20), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('unique_clients', sa.Integer(), nullable=False),
    sa.Column('total_premium', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_accumulation', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('companies_json', sa.JSON(), nullable=False),
    sa.Column('product_types_json', sa.JSON(), nullable=False),
    sa.Column('top_clients_json', sa.JSON(), nullable=False),
    sa.Column('changes_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['file_uploads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id')
    )
    op.create_index('ix_production_summaries_user_date', 'production_summaries', ['user_id', 'upload_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_production_summaries_user_date', table_name='production_summaries')
    op.drop_table('production_summaries')
    # ### end Alembic commands ###
