"""add_volume_commission_rates

Revision ID: a055c0880c5c
Revises: edf3a820f429
Create Date: 2026-03-16 22:53:54.289607
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a055c0880c5c'
down_revision: Union[str, None] = 'edf3a820f429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volume_commission_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('nifraim_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('volume_rate_per_million', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pension_accumulation', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('changed_percent', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('conversion_to_annuity', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('payment_frequency', sa.String(length=20), nullable=True),
    sa.Column('paid_to', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volume_commission_rates')
    # ### end Alembic commands ###
