"""add debts table

Revision ID: a0586c3abe01
Revises: 8d8f02d23630
Create Date: 2026-04-19 00:04:04.911537
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a0586c3abe01'
down_revision: Union[str, None] = '8d8f02d23630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('customer_id_number', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('product', sa.String(length=100), nullable=True),
    sa.Column('policy_number', sa.String(length=50), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('premium', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('accumulation', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(), nullable=True),
    sa.Column('production_upload_id', sa.UUID(), nullable=False),
    sa.Column('commission_upload_id', sa.UUID(), nullable=True),
    sa.Column('last_emailed_at', sa.DateTime(), nullable=True),
    sa.Column('email_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commission_upload_id'], ['file_uploads.id'], ),
    sa.ForeignKeyConstraint(['production_upload_id'], ['file_uploads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_debts_user_company', 'debts', ['user_id', 'company_name'], unique=False)
    op.create_index('ix_debts_user_customer', 'debts', ['user_id', 'customer_id_number'], unique=False)
    op.create_index('ix_debts_user_status', 'debts', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_debts_user_status', table_name='debts')
    op.drop_index('ix_debts_user_customer', table_name='debts')
    op.drop_index('ix_debts_user_company', table_name='debts')
    op.drop_table('debts')
    # ### end Alembic commands ###
