"""add_category_to_recruits

Revision ID: b4cefe3b81b5
Revises: 4328cb5647d0
Create Date: 2026-04-18 10:59:36.015569
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b4cefe3b81b5'
down_revision: Union[str, None] = '4328cb5647d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruits', sa.Column('category', sa.String(length=20), server_default='financial', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruits', 'category')
    # ### end Alembic commands ###
