"""add_portal_snapshots

Revision ID: c9f9588cb2d0
Revises: h8c9d0e1f2g3
Create Date: 2026-03-13 19:29:30.854115
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c9f9588cb2d0'
down_revision: Union[str, None] = 'h8c9d0e1f2g3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portal_link_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('customer_id_number', sa.String(length=20), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('period_label', sa.String(length=100), nullable=False),
    sa.Column('kpi_json', sa.JSON(), nullable=False),
    sa.Column('products_json', sa.JSON(), nullable=False),
    sa.Column('company_breakdown_json', sa.JSON(), nullable=False),
    sa.Column('has_changes', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('changes_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portal_link_id'], ['customer_portal_links.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['file_uploads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portal_snapshots_link_date', 'portal_snapshots', ['portal_link_id', 'snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_portal_snapshots_link_date', table_name='portal_snapshots')
    op.drop_table('portal_snapshots')
    # ### end Alembic commands ###
