"""maslaka agent links (שיוך לבית תוכנה)

Hand-written, NOT autogenerated: this database carries pre-existing drift from
the models, so `--autogenerate` sweeps unrelated churn into the revision. Only
the new table is described here.

Revision ID: mslk_shiyuch_01
Revises: b7c8d9e0f1a2
Create Date: 2026-09-24
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "mslk_shiyuch_01"
down_revision: Union[str, Sequence[str], None] = "b7c8d9e0f1a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "maslaka_agent_links",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("user_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("agent_id_number", sa.String(20), nullable=True),
        sa.Column("agent_name", sa.String(255), nullable=True),
        sa.Column("agent_licence_number", sa.String(32), nullable=True),
        sa.Column("status", sa.String(24), nullable=False, server_default="not_started"),
        sa.Column("form_downloaded_at", sa.DateTime(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("rejected_reason", sa.String(500), nullable=True),
        sa.Column("signed_pdf", sa.LargeBinary(), nullable=True),
        sa.Column("signed_pdf_filename", sa.String(255), nullable=True),
        sa.Column("delivery_note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")),
    )
    # One association per user — the flow is per-agent, and a second row would
    # make "which one gates the tab?" ambiguous.
    op.create_index("ix_maslaka_agent_links_user_id", "maslaka_agent_links",
                    ["user_id"], unique=True)


def downgrade() -> None:
    op.drop_index("ix_maslaka_agent_links_user_id", table_name="maslaka_agent_links")
    op.drop_table("maslaka_agent_links")
